- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Import VPC Variables
    include_vars: vars/vpc-setup

  - name: Create studybix VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidr}}"
      region: "{{region}}"
      dns_support: yes
      dns_hostnames: yes
      tenancy: default
      state: present
    register: vpcout

  #- debug:
   #   var: vpcout

  - name: create the public subnet 1
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PubSub3Cidr}}"
      az: "{{zone1}}"
      region: "{{region}}"
      map_public: yes
      resource_tags:
        Name: StudyBix-Pubsub1
    register: pubsub1_out

  - name: create the public subnet 2
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PubSub1Cidr}}"
      az: "{{zone2}}"
      region: "{{region}}"
      map_public: yes
      resource_tags:
        Name: StudyBix-Pubsub2
    register: pubsub2_out

  - name: create the public subnet 3
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PubSub2Cidr}}"
      az: "{{zone3}}"
      region: "{{region}}"
      map_public: yes
      resource_tags:
        Name: StudyBix-Pubsub3
    register: pubsub3_out

# Private Subnet code

  - name: create the Private subnet 1
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PrivSub1Cidr}}"
      az: "{{zone1}}"
      region: "{{region}}"
      map_public: yes
      resource_tags:
        Name: StudyBix-Privatesub1
    register: privatesub1_out

  - name: create the private subnet 2
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PrivSub2Cidr}}"
      az: "{{zone2}}"
      region: "{{region}}"
      map_public: yes
      resource_tags:
        Name: StudyBix-Privatesub2
    register: privatesub2_out

  - name: create the private subnet 3
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PrivSub3Cidr}}"
      az: "{{zone3}}
      region: "{{region}}"
      map_public: yes
      resource_tags:
        Name: StudyBix-Privatesub3
    register: privatesub3_out